name: unihub
description: A platform dedicated for vloggers, this app is created for the community of vloggers to help each other out.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^0.3.1
  flutter_reaction_button:
  badges:
  timeago:
  fancy_bottom_navigation:
  dynamic_theme:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  feather_icons_flutter:
  eva_icons_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica-neue/Thin.ttf
          weight: 100
        - asset: fonts/helvetica-neue/Light.ttf
          weight: 300
        - asset: fonts/helvetica-neue/Regular.ttf
          weight: 400
        - asset: fonts/helvetica-neue/Medium.ttf
          weight: 500
        - asset: fonts/helvetica-neue/Bold.ttf
          weight: 700
        - asset: fonts/helvetica-neue/Heavy.ttf
          weight: 900

    - family: Supra
      fonts:
        - asset: fonts/supra-mezzo/Supra-XLightMezzo.ttf
          weight: 200
        - asset: fonts/supra-mezzo/Supra-LightMezzo.ttf
          weight: 300
        - asset: fonts/supra-mezzo/Supra-NormalMezzo.ttf
          weight: 400
        - asset: fonts/supra-mezzo/Supra-MediumMezzo.ttf
          weight: 500
        - asset: fonts/supra-mezzo/Supra-DemiboldMezzo.ttf
          weight: 600
        - asset: fonts/supra-mezzo/Supra-BoldMezzo.ttf
          weight: 700
        - asset: fonts/supra-mezzo/Supra-XBoldMezzo.ttf
          weight: 800
        - asset: fonts/supra-mezzo/Supra-BlackMezzo.ttf
          weight: 900

        - asset: fonts/supra-mezzo/Supra-XLightMezzoItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/supra-mezzo/Supra-LightMezzoItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/supra-mezzo/Supra-NormalMezzoItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/supra-mezzo/Supra-MediumMezzoItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/supra-mezzo/Supra-DemiboldMezzoItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/supra-mezzo/Supra-BoldMezzoItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/supra-mezzo/Supra-XBoldMezzoItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/supra-mezzo/Supra-BlackMezzoItalic.ttf
          style: italic
          weight: 900
